backend: add prod env variable configuration to floodcast

diff --git a/backend/floodcast/Makefile b/backend/floodcast/Makefile
--- a/backend/floodcast/Makefile
+++ b/backend/floodcast/Makefile
@@ -1,6 +1,20 @@
 IMAGE_NAME := floodcast-app
 
-.PHONY: build run clean fclean
+.PHONY: build run clean fclean localenv prodenv
+
+localenv:
+	@echo "Creating .env for local development..."
+	@echo "MONGO_URI=\"mongodb://host.docker.internal:27017\"" > .env
+	@echo ".env created with local MONGO_URI."
+
+prodenv:
+	@echo "Creating .env for production environment..." && \
+	if [ -z "$$MONGO_URI" ]; then \
+		echo "Error: MONGO_URI environment variable is not set. Please set it before running 'make prodenv'."; \
+		exit 1; \
+	fi && \
+	echo "MONGO_URI=\"$$MONGO_URI\"" > .env && \
+	echo ".env created with production MONGO_URI."
 
 build: clean
 	@echo "Building Docker image $(IMAGE_NAME) with BuildKit..."
@@ -11,6 +25,7 @@ run:
 	@echo "Running Docker container $(IMAGE_NAME)..."
 	docker run --rm --add-host=host.docker.internal:host-gateway $(IMAGE_NAME)
 	@echo "Container stopped."
+
 
 clean:
 	@echo "Cleaning up dangling Docker images and stopped containers..."
